-- UK Air Quality schema (bigint IDs + external *_ref fields)
-- External identifiers that arrive as text (even if numeric) use *_ref.
-- Internal joins always use bigint *_id columns.
-- Safe to rerun; uses IF NOT EXISTS where appropriate.

-- Ensure needed extensions
-- PostGIS remains in public on Supabase hosted Postgres.
create extension if not exists postgis;
create extension if not exists pgcrypto;

-- Connectors (external data sources)
do $$
begin
  if to_regclass('public.services') is not null
     and to_regclass('public.connectors') is null then
    alter table public.services rename to connectors;
  end if;
end $$;

create table if not exists connectors (
  id bigint generated by default as identity primary key,
  connector_code text not null,
  label text not null,
  service_url text,
  poll_enabled boolean default true,
  poll_interval_minutes int default 60,
  poll_window_hours int default 6,
  poll_timeseries_batch_size int,
  stations_bbox_supported boolean default true,
  timeseries_station_filter_supported boolean default true,
  last_polled_at timestamptz,
  created_at timestamptz default now()
);

do $$
begin
  if to_regclass('public.connectors') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'connectors'
         and column_name = 'service_code'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'connectors'
         and column_name = 'connector_code'
     ) then
    alter table public.connectors rename column service_code to connector_code;
  end if;
end $$;

alter table if exists connectors add column if not exists connector_code text;
drop index if exists services_service_code_uidx;
drop index if exists services_service_ref_uidx;
create unique index if not exists connectors_connector_code_uidx on connectors(connector_code);

-- Default flags for known connectors (applies on insert; update existing rows if present).
create or replace function connectors_apply_known_defaults()
returns trigger
set search_path = public, pg_catalog
as $$
begin
  if new.service_url = 'https://uk-air.defra.gov.uk/sos-ukair/api/v1'
     or new.label = 'UK-AIR-SOS' then
    new.stations_bbox_supported = false;
    new.timeseries_station_filter_supported = false;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists connectors_apply_known_defaults on connectors;
create trigger connectors_apply_known_defaults
before insert on connectors
for each row execute function connectors_apply_known_defaults();

update connectors
set stations_bbox_supported = false,
    timeseries_station_filter_supported = false,
    poll_timeseries_batch_size = null
where service_url = 'https://uk-air.defra.gov.uk/sos-ukair/api/v1'
   or label = 'UK-AIR-SOS';

update connectors
set connector_code = 'uk_air_sos'
where id = 1;

-- Categories
create table if not exists categories (
  id bigint generated by default as identity primary key,
  category_ref text not null,
  label text not null,
  connector_id bigint not null references connectors(id) on delete cascade
);
create unique index if not exists categories_connector_ref_uidx on categories(connector_id, category_ref);

do $$
begin
  if to_regclass('public.categories') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'categories'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'categories'
         and column_name = 'connector_id'
     ) then
    alter table public.categories rename column service_id to connector_id;
  end if;
end $$;

-- Phenomena (pollutants)
create table if not exists phenomena (
  id bigint generated by default as identity primary key,
  label text not null,
  eionet_uri text,
  notation text,
  pollutant_label text,
  connector_id bigint not null references connectors(id) on delete cascade
);
drop index if exists phenomena_service_eionet_uidx;
create unique index if not exists phenomena_service_eionet_uidx
  on phenomena(connector_id, eionet_uri);

do $$
begin
  if to_regclass('public.phenomena') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'phenomena'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'phenomena'
         and column_name = 'connector_id'
     ) then
    alter table public.phenomena rename column service_id to connector_id;
  end if;
end $$;

-- Offerings
create table if not exists offerings (
  id bigint generated by default as identity primary key,
  offering_ref text not null,
  label text not null,
  service_ref text not null,
  connector_id bigint not null references connectors(id) on delete cascade
);
create unique index if not exists offerings_connector_ref_uidx
  on offerings(connector_id, service_ref, offering_ref);

do $$
begin
  if to_regclass('public.offerings') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'offerings'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'offerings'
         and column_name = 'connector_id'
     ) then
    alter table public.offerings rename column service_id to connector_id;
  end if;
end $$;

alter table if exists offerings add column if not exists service_ref text;

-- Features of interest (sites/areas)
create table if not exists features (
  id bigint generated by default as identity primary key,
  feature_ref text not null,
  label text not null,
  geometry geography(Point, 4326),
  service_ref text not null,
  connector_id bigint not null references connectors(id) on delete cascade
);
create unique index if not exists features_connector_ref_uidx
  on features(connector_id, service_ref, feature_ref);

do $$
begin
  if to_regclass('public.features') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'features'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'features'
         and column_name = 'connector_id'
     ) then
    alter table public.features rename column service_id to connector_id;
  end if;
end $$;

alter table if exists features add column if not exists service_ref text;

-- Procedures (sensors/methods)
create table if not exists procedures (
  id bigint generated by default as identity primary key,
  procedure_ref text not null,
  label text not null,
  raw_formats text[],
  service_ref text not null,
  connector_id bigint not null references connectors(id) on delete cascade
);
create unique index if not exists procedures_connector_ref_uidx
  on procedures(connector_id, service_ref, procedure_ref);

do $$
begin
  if to_regclass('public.procedures') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'procedures'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'procedures'
         and column_name = 'connector_id'
     ) then
    alter table public.procedures rename column service_id to connector_id;
  end if;
end $$;

alter table if exists procedures add column if not exists service_ref text;

-- Stations
create table if not exists stations (
  id bigint generated by default as identity primary key,
  station_ref text not null,
  service_ref text not null,
  label text not null,
  station_name text,
  station_type text,
  region text,
  la_code text,
  la_version text,
  pcon_code text,
  pcon_version text,
  geometry geography(Point, 4326),
  connector_id bigint not null references connectors(id) on delete cascade,
  category_id bigint references categories(id),
  first_seen_at timestamptz default now(),
  last_seen_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz default now()
);
create unique index if not exists stations_connector_ref_uidx
  on stations(connector_id, service_ref, station_ref);
create index if not exists stations_geom_idx on stations using gist (geometry);
create index if not exists stations_la_code_idx on stations(la_code);
create index if not exists stations_la_version_idx on stations(la_version);

do $$
begin
  if to_regclass('public.stations') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'stations'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'stations'
         and column_name = 'connector_id'
     ) then
    alter table public.stations rename column service_id to connector_id;
  end if;
end $$;

alter table if exists stations add column if not exists service_ref text;

alter table if exists stations add column if not exists la_code text;
alter table if exists stations add column if not exists la_version text;
alter table if exists stations add column if not exists pcon_code text;
alter table if exists stations add column if not exists pcon_version text;
alter table if exists stations add column if not exists station_name text;

create index if not exists stations_pcon_code_idx on stations(pcon_code);
create index if not exists stations_pcon_version_idx on stations(pcon_version);

-- Local Authority boundaries (used to persist station LA codes)
create table if not exists la_boundaries (
  id bigint generated by default as identity primary key,
  la_code text not null,
  la_name text,
  la_version text not null,
  geometry geography(MultiPolygon, 4326),
  created_at timestamptz default now()
);
create unique index if not exists la_boundaries_code_version_uidx
  on la_boundaries(la_code, la_version);
create index if not exists la_boundaries_geom_idx on la_boundaries using gist (geometry);

create or replace function uk_aq_refresh_station_la_codes(target_version text)
returns integer
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  updated_count integer;
begin
  update stations st
  set la_code = lb.la_code,
      la_version = lb.la_version
  from la_boundaries lb
  where lb.la_version = target_version
    and st.geometry is not null
    and lb.geometry is not null
    and ST_Covers(lb.geometry::geometry, st.geometry::geometry);
  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

-- Parliamentary Constituency boundaries (used to persist station PCON codes)
create table if not exists pcon_boundaries (
  id bigint generated by default as identity primary key,
  pcon_code text not null,
  pcon_name text,
  pcon_version text not null,
  geometry geography(MultiPolygon, 4326),
  created_at timestamptz default now()
);
create unique index if not exists pcon_boundaries_code_version_uidx
  on pcon_boundaries(pcon_code, pcon_version);
create index if not exists pcon_boundaries_geom_idx on pcon_boundaries using gist (geometry);

create or replace function uk_aq_refresh_station_pcon_codes(target_version text)
returns integer
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  updated_count integer;
begin
  update stations st
  set pcon_code = pb.pcon_code,
      pcon_version = pb.pcon_version
  from pcon_boundaries pb
  where pb.pcon_version = target_version
    and st.geometry is not null
    and pb.geometry is not null
    and (st.pcon_code is null or st.pcon_version is distinct from target_version)
    and ST_Covers(pb.geometry::geometry, st.geometry::geometry);
  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

create or replace function uk_aq_refresh_station_pcon_codes_partition(
  target_version text,
  partition_mod integer,
  partition_idx integer
)
returns integer
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  updated_count integer;
begin
  if partition_mod <= 0 then
    raise exception 'partition_mod must be > 0';
  end if;
  if partition_idx < 0 or partition_idx >= partition_mod then
    raise exception 'partition_idx must be between 0 and %', partition_mod - 1;
  end if;

  update stations st
  set pcon_code = pb.pcon_code,
      pcon_version = pb.pcon_version
  from pcon_boundaries pb
  where pb.pcon_version = target_version
    and st.geometry is not null
    and pb.geometry is not null
    and (st.pcon_code is null or st.pcon_version is distinct from target_version)
    and mod(st.id, partition_mod::bigint) = partition_idx::bigint
    and ST_Covers(pb.geometry::geometry, st.geometry::geometry);
  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

-- Station PCON history (snapshot per boundary version)
create table if not exists station_pcon_history (
  id bigint generated by default as identity primary key,
  station_id bigint not null references stations(id) on delete cascade,
  pcon_code text not null,
  pcon_name text,
  pcon_version text not null,
  computed_at timestamptz default now()
);
create unique index if not exists station_pcon_history_station_version_uidx
  on station_pcon_history(station_id, pcon_version);
create index if not exists station_pcon_history_pcon_code_idx
  on station_pcon_history(pcon_code);
create index if not exists station_pcon_history_pcon_version_idx
  on station_pcon_history(pcon_version);

create or replace function uk_aq_refresh_station_pcon_history(target_version text)
returns integer
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  upserted_count integer;
begin
  perform set_config('statement_timeout', '15min', true);
  insert into station_pcon_history (station_id, pcon_code, pcon_name, pcon_version)
  select
    st.id,
    pb.pcon_code,
    pb.pcon_name,
    pb.pcon_version
  from stations st
  join pcon_boundaries pb
    on pb.pcon_version = target_version
  where st.geometry is not null
    and pb.geometry is not null
    and ST_Covers(pb.geometry::geometry, st.geometry::geometry)
  on conflict (station_id, pcon_version) do update
  set pcon_code = excluded.pcon_code,
      pcon_name = excluded.pcon_name,
      computed_at = now();
  get diagnostics upserted_count = row_count;
  return upserted_count;
end;
$$;

create or replace function uk_aq_refresh_station_pcon_history_partition(
  target_version text,
  partition_mod int,
  partition_idx int
)
returns integer
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  upserted_count integer;
begin
  if partition_mod is null or partition_mod <= 0 then
    raise exception 'partition_mod must be > 0';
  end if;
  if partition_idx is null or partition_idx < 0 or partition_idx >= partition_mod then
    raise exception 'partition_idx must be between 0 and partition_mod - 1';
  end if;

  perform set_config('statement_timeout', '15min', true);
  insert into station_pcon_history (station_id, pcon_code, pcon_name, pcon_version)
  select
    st.id,
    pb.pcon_code,
    pb.pcon_name,
    pb.pcon_version
  from stations st
  join pcon_boundaries pb
    on pb.pcon_version = target_version
  where st.geometry is not null
    and pb.geometry is not null
    and mod(st.id, partition_mod) = partition_idx
    and ST_Covers(pb.geometry::geometry, st.geometry::geometry)
  on conflict (station_id, pcon_version) do update
  set pcon_code = excluded.pcon_code,
      pcon_name = excluded.pcon_name,
      computed_at = now();
  get diagnostics upserted_count = row_count;
  return upserted_count;
end;
$$;

create or replace function uk_aq_stations_with_pcon(target_version text)
returns table (
  station_id bigint,
  station_ref text,
  label text,
  station_type text,
  region text,
  la_code text,
  la_version text,
  pcon_code text,
  pcon_name text,
  pcon_version text,
  geometry geography(Point, 4326),
  connector_id bigint,
  category_id bigint,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz
)
language sql
set search_path = public, pg_catalog
as $$
  select
    st.id as station_id,
    st.station_ref,
    st.label,
    st.station_type,
    st.region,
    st.la_code,
    st.la_version,
    sph.pcon_code,
    sph.pcon_name,
    sph.pcon_version,
    st.geometry,
    st.connector_id,
    st.category_id,
    st.first_seen_at,
    st.last_seen_at,
    st.removed_at,
    st.created_at
  from stations st
  left join station_pcon_history sph
    on sph.station_id = st.id
    and sph.pcon_version = target_version;
$$;

create or replace function uk_aq_fix_station_geometry_swapped()
returns integer
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  updated_count integer;
begin
  update stations
  set geometry = ST_SetSRID(
    ST_MakePoint(
      ST_Y(geometry::geometry),
      ST_X(geometry::geometry)
    ),
    4326
  )::geography
  where geometry is not null
    and ST_X(geometry::geometry) between 49 and 61
    and ST_Y(geometry::geometry) between -10 and 10;
  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

-- Parliamentary constituencies (current + legacy electorates)
create table if not exists pcon_current (
  id bigint generated by default as identity primary key,
  gss_code text not null,
  name text not null,
  electorate int,
  region text,
  country text,
  created_at timestamptz default now()
);
create unique index if not exists pcon_current_gss_code_uidx on pcon_current(gss_code);

create table if not exists pcon_legacy (
  id bigint generated by default as identity primary key,
  gss_code text not null,
  name text not null,
  electorate int,
  region text,
  country text,
  created_at timestamptz default now()
);
create unique index if not exists pcon_legacy_gss_code_uidx on pcon_legacy(gss_code);

-- Canonical GSS codes registry (shared across geographies)
create table if not exists gss_codes (
  id bigint generated by default as identity primary key,
  gss_code text not null,
  name text,
  geography_type text,
  valid_from date,
  valid_to date
);
create unique index if not exists gss_codes_gss_code_uidx on gss_codes(gss_code);

-- GSS region name lookup (hex map metadata)
create table if not exists uk_aq_region_names (
  region_code text primary key,
  region_name text not null,
  created_at timestamptz default now()
);

insert into uk_aq_region_names (region_code, region_name)
values
  ('E12000001', 'North East'),
  ('E12000002', 'North West'),
  ('E12000003', 'Yorkshire and The Humber'),
  ('E12000004', 'East Midlands'),
  ('E12000005', 'West Midlands'),
  ('E12000006', 'East of England'),
  ('E12000007', 'London'),
  ('E12000008', 'South East'),
  ('E12000009', 'South West'),
  ('S92000003', 'Scotland'),
  ('W92000004', 'Wales'),
  ('N92000002', 'Northern Ireland')
on conflict (region_code) do update
set region_name = excluded.region_name;

-- Air quality guideline limits (WHO/UK/EU, etc.)
create table if not exists uk_aq_guidelines (
  id bigint generated by default as identity primary key,
  pollutant text not null,
  averaging_period_label text not null,
  averaging_period_interval interval,
  level_label text not null,
  limit_value numeric not null,
  uom text not null,
  source text,
  notes text,
  valid_from date,
  valid_to date,
  created_at timestamptz default now()
);
create unique index if not exists uk_aq_guidelines_uidx
  on uk_aq_guidelines(pollutant, averaging_period_label, level_label, source);

-- Timeseries metadata
create table if not exists timeseries (
  id bigint generated by default as identity primary key,
  timeseries_ref text not null,
  label text not null,
  uom text,
  station_id bigint references stations(id) on delete cascade,
  service_ref text not null,
  connector_id bigint not null references connectors(id) on delete cascade,
  offering_id bigint references offerings(id),
  feature_id bigint references features(id),
  procedure_id bigint references procedures(id),
  phenomenon_id bigint references phenomena(id),
  category_id bigint references categories(id),
  first_value_at timestamptz,
  last_value_at timestamptz,
  last_value numeric,
  extras jsonb,
  rendering_hints jsonb,
  status_intervals jsonb,
  created_at timestamptz default now()
);
create unique index if not exists timeseries_connector_ref_uidx
  on timeseries(connector_id, service_ref, timeseries_ref);
create index if not exists timeseries_station_idx on timeseries(station_id);
create index if not exists timeseries_phenomenon_idx on timeseries(phenomenon_id);
create index if not exists timeseries_phenomenon_station_idx on timeseries(phenomenon_id, station_id);

do $$
begin
  if to_regclass('public.timeseries') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'timeseries'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'timeseries'
         and column_name = 'connector_id'
     ) then
    alter table public.timeseries rename column service_id to connector_id;
  end if;
end $$;

alter table if exists timeseries add column if not exists service_ref text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'connectors'
      and column_name = 'service_ref'
  ) then
    update stations st
    set service_ref = coalesce(st.service_ref, conn.service_ref, conn.connector_code)
    from connectors conn
    where st.connector_id = conn.id
      and st.service_ref is null;

    update timeseries ts
    set service_ref = coalesce(ts.service_ref, conn.service_ref, conn.connector_code)
    from connectors conn
    where ts.connector_id = conn.id
      and ts.service_ref is null;

    update offerings off
    set service_ref = coalesce(off.service_ref, conn.service_ref, conn.connector_code)
    from connectors conn
    where off.connector_id = conn.id
      and off.service_ref is null;

    update features feat
    set service_ref = coalesce(feat.service_ref, conn.service_ref, conn.connector_code)
    from connectors conn
    where feat.connector_id = conn.id
      and feat.service_ref is null;

    update procedures proc
    set service_ref = coalesce(proc.service_ref, conn.service_ref, conn.connector_code)
    from connectors conn
    where proc.connector_id = conn.id
      and proc.service_ref is null;
  end if;
end $$;

alter table if exists connectors drop column if exists service_ref;

alter table if exists connectors alter column connector_code set not null;
alter table if exists stations alter column service_ref set not null;
alter table if exists timeseries alter column service_ref set not null;
alter table if exists offerings alter column service_ref set not null;
alter table if exists features alter column service_ref set not null;
alter table if exists procedures alter column service_ref set not null;

-- Reference values attached to a timeseries
create table if not exists reference_values (
  id uuid default gen_random_uuid() primary key,
  timeseries_id bigint references timeseries(id) on delete cascade,
  name text,
  color text,
  value numeric,
  created_at timestamptz default now()
);

-- Observations (time-value pairs)
create table if not exists observations (
  timeseries_id bigint references timeseries(id) on delete cascade,
  observed_at timestamptz not null,
  value numeric,
  status text,
  created_at timestamptz default now(),
  primary key (timeseries_id, observed_at)
);
create index if not exists observations_time_idx on observations(observed_at);

-- Error logs
create table if not exists error_logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default now(),
  source text not null,
  severity text not null,
  message text not null,
  stack text,
  context jsonb,
  connector_id bigint references connectors(id) on delete set null,
  station_id bigint references stations(id) on delete set null,
  timeseries_id bigint references timeseries(id) on delete set null,
  dropbox_path text
);
create index if not exists error_logs_created_at_idx on error_logs(created_at desc);
create index if not exists error_logs_source_idx on error_logs(source);
create index if not exists error_logs_connector_idx on error_logs(connector_id);

do $$
begin
  if to_regclass('public.error_logs') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'error_logs'
         and column_name = 'service_id'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'error_logs'
         and column_name = 'connector_id'
     ) then
    alter table public.error_logs rename column service_id to connector_id;
  end if;
end $$;

-- PM2.5 Population Exposure Indicator progress (PERT)
create table if not exists pm25_population_exposure (
  id bigint generated by default as identity primary key,
  year int unique,
  pei_base numeric,
  pei numeric,
  yearly_change numeric,
  cumulative_change numeric,
  cumulative_change_pct numeric,
  collected_at timestamptz default now()
);

-- PM2.5 Annual Mean Concentration Target stats (AMCT)
create table if not exists pm25_amct_sites (
  id bigint generated by default as identity primary key,
  site_code text,
  site_name text,
  year int,
  annual_mean numeric,
  exceeded_interim boolean,
  exceeded_final boolean,
  data_capture_ok boolean,
  collected_at timestamptz default now()
);
create index if not exists pm25_amct_site_year_idx on pm25_amct_sites(site_code, year);

-- ----------------------------
-- Row Level Security (RLS)
-- ----------------------------
-- Enable RLS on all tables and add safe-to-reapply policies:
--   - authenticated + service_role: read
--   - service_role: write
-- Assumes Supabase roles where auth.role() is available.

-- Enable RLS
alter table if exists connectors enable row level security;
alter table if exists categories enable row level security;
alter table if exists phenomena enable row level security;
alter table if exists offerings enable row level security;
alter table if exists features enable row level security;
alter table if exists procedures enable row level security;
alter table if exists stations enable row level security;
alter table if exists timeseries enable row level security;
alter table if exists reference_values enable row level security;
alter table if exists observations enable row level security;
alter table if exists error_logs enable row level security;
alter table if exists pm25_population_exposure enable row level security;
alter table if exists pm25_amct_sites enable row level security;
alter table if exists la_boundaries enable row level security;
alter table if exists pcon_boundaries enable row level security;
alter table if exists station_pcon_history enable row level security;
alter table if exists pcon_current enable row level security;
alter table if exists pcon_legacy enable row level security;
alter table if exists gss_codes enable row level security;
alter table if exists uk_aq_region_names enable row level security;
alter table if exists uk_aq_guidelines enable row level security;

-- Helper DO block to add policies idempotently
do $$
declare
  t text;
begin
  for t in select unnest(array[
    'connectors','categories','phenomena','offerings','features','procedures','stations','timeseries','reference_values','observations','pm25_population_exposure','pm25_amct_sites','la_boundaries','pcon_boundaries','station_pcon_history','pcon_current','pcon_legacy','gss_codes','uk_aq_region_names','uk_aq_guidelines'
  ])
  loop
    -- Read policy for authenticated + service_role
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = current_schema()
        and p.tablename = t
        and p.policyname = t || '_select_authenticated'
    ) then
      execute format(
        'create policy %I on %I for select using (auth.role() in (''authenticated'',''service_role''));',
        t || '_select_authenticated', t
      );
    end if;

    -- Write policy for service_role
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = current_schema()
        and p.tablename = t
        and p.policyname = t || '_write_service_role'
    ) then
      execute format(
        'create policy %I on %I for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'');',
        t || '_write_service_role', t
      );
    end if;
  end loop;
end $$;

-- error_logs policies: service_role only
do $$
begin
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = current_schema()
      and p.tablename = 'error_logs'
      and p.policyname = 'error_logs_select_service_role'
  ) then
    execute
      'create policy error_logs_select_service_role on error_logs for select using (auth.role() = ''service_role'');';
  end if;

  if not exists (
    select 1 from pg_policies p
    where p.schemaname = current_schema()
      and p.tablename = 'error_logs'
      and p.policyname = 'error_logs_write_service_role'
  ) then
    execute
      'create policy error_logs_write_service_role on error_logs for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'');';
  end if;
end $$;

-- pollutant_thresholds policies (table is created in uk_air_quality_views.sql)
alter table if exists pollutant_thresholds enable row level security;

do $$
begin
  if to_regclass('public.pollutant_thresholds') is null then
    return;
  end if;

  if not exists (
    select 1 from pg_policies p
    where p.schemaname = current_schema()
      and p.tablename = 'pollutant_thresholds'
      and p.policyname = 'pollutant_thresholds_select_authenticated'
  ) then
    execute
      'create policy pollutant_thresholds_select_authenticated on pollutant_thresholds '
      'for select using (auth.role() in (''authenticated'',''service_role''));';
  end if;

  if not exists (
    select 1 from pg_policies p
    where p.schemaname = current_schema()
      and p.tablename = 'pollutant_thresholds'
      and p.policyname = 'pollutant_thresholds_write_service_role'
  ) then
    execute
      'create policy pollutant_thresholds_write_service_role on pollutant_thresholds '
      'for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'');';
  end if;
end $$;

-- PostGIS system table: enable RLS if we own it; otherwise skip.
do $$
declare
  owner_name text;
begin
  select r.rolname into owner_name
  from pg_class c
  join pg_roles r on r.oid = c.relowner
  where c.relname = 'spatial_ref_sys'
    and c.relnamespace = 'public'::regnamespace;

  if owner_name is null then
    raise notice 'spatial_ref_sys not found; skipping RLS setup.';
    return;
  end if;

  if owner_name = current_user then
    execute 'alter table public.spatial_ref_sys enable row level security';
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = current_schema()
        and p.tablename = 'spatial_ref_sys'
        and p.policyname = 'spatial_ref_sys_select_all'
    ) then
      execute
        'create policy spatial_ref_sys_select_all on public.spatial_ref_sys for select using (auth.role() in (''anon'',''authenticated'',''service_role''));';
    end if;
  else
    raise notice 'Skipping RLS on public.spatial_ref_sys; owner is %, current_user is %', owner_name, current_user;
  end if;
exception when insufficient_privilege then
  raise notice 'Skipping RLS on public.spatial_ref_sys due to insufficient privileges.';
end $$;
