name = "uk-aq-dispatcher"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/2 * * * *"]

[observability]
enabled = true

secrets_store = [
  { binding = "SB_UK_AQ_CRON_SECRET", store_id = "b516fa0fe5c54089a75898286a4c6234", secret_name = "SB_UK_AQ_CRON_SECRET" },
  { binding = "SUPABASE_ANON_JWT", store_id = "b516fa0fe5c54089a75898286a4c6234", secret_name = "SUPABASE_ANON_JWT" },
  { binding = "SUPABASE_URL", store_id = "b516fa0fe5c54089a75898286a4c6234", secret_name = "SUPABASE_URL" }
]
