-- Migration: switch to bigint internal IDs for stations/timeseries/observations.
-- Run this once after applying the updated schema.

-- 1) Stations: rename text id -> source_id, add bigint id
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'stations' and column_name = 'id' and data_type = 'text'
  ) then
    execute 'alter table stations rename column id to source_id';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'stations' and column_name = 'id'
  ) then
    execute 'alter table stations add column id bigint generated by default as identity';
  end if;
end $$;
alter table stations alter column source_id set not null;
alter table stations drop constraint if exists stations_pkey;
alter table stations add constraint stations_pkey primary key (id);
alter table stations drop constraint if exists stations_service_source_uidx;
alter table stations add constraint stations_service_source_uidx unique (service_id, source_id);

-- 2) Timeseries: rename text id -> source_id, add bigint id
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'timeseries' and column_name = 'id' and data_type = 'text'
  ) then
    execute 'alter table timeseries rename column id to source_id';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'timeseries' and column_name = 'id'
  ) then
    execute 'alter table timeseries add column id bigint generated by default as identity';
  end if;
end $$;
alter table timeseries alter column source_id set not null;
alter table timeseries drop constraint if exists timeseries_pkey;
alter table timeseries add constraint timeseries_pkey primary key (id);
alter table timeseries drop constraint if exists timeseries_service_source_uidx;
alter table timeseries add constraint timeseries_service_source_uidx unique (service_id, source_id);

-- 3) Timeseries station mapping: convert station_id to bigint
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'timeseries' and column_name = 'station_id' and data_type = 'text'
  ) then
    execute 'alter table timeseries rename column station_id to station_source_id';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'timeseries' and column_name = 'station_id'
  ) then
    execute 'alter table timeseries add column station_id bigint';
  end if;
end $$;

update timeseries ts
set station_id = stn.id
from stations stn
where ts.station_id is null
  and ts.station_source_id is not null
  and stn.service_id = ts.service_id
  and stn.source_id = ts.station_source_id;

alter table timeseries drop constraint if exists timeseries_station_id_fkey;
alter table timeseries add constraint timeseries_station_id_fkey
  foreign key (station_id) references stations(id) on delete cascade;

-- Optional cleanup after verification:
-- alter table timeseries drop column if exists station_source_id;

-- 4) Reference values: switch timeseries_id to bigint
alter table reference_values add column if not exists timeseries_id_bigint bigint;
update reference_values rv
set timeseries_id_bigint = ts.id
from timeseries ts
where rv.timeseries_id_bigint is null
  and rv.timeseries_id::text = ts.source_id;

alter table reference_values drop constraint if exists reference_values_timeseries_id_fkey;
alter table reference_values drop column if exists timeseries_id;
alter table reference_values rename column timeseries_id_bigint to timeseries_id;
alter table reference_values add constraint reference_values_timeseries_id_fkey
  foreign key (timeseries_id) references timeseries(id) on delete cascade;

-- 5) Observations: switch timeseries_id to bigint and primary key
alter table observations add column if not exists timeseries_id_bigint bigint;
update observations obs
set timeseries_id_bigint = ts.id
from timeseries ts
where obs.timeseries_id_bigint is null
  and obs.timeseries_id::text = ts.source_id;

alter table observations drop constraint if exists observations_pkey;
alter table observations drop column if exists timeseries_id;
alter table observations rename column timeseries_id_bigint to timeseries_id;
alter table observations alter column timeseries_id set not null;
alter table observations add constraint observations_pkey primary key (timeseries_id, observed_at);
alter table observations add constraint observations_timeseries_fkey
  foreign key (timeseries_id) references timeseries(id) on delete cascade;
